// This source file was auto-generated by ClassMate++
// Created: 26 Jan 2019 8:47:47 pm
// Copyright (c) 2019, HurleyWorks

#include "berserkpch.h"
#include "App.h"

namespace Jahley
{
    using namespace std::chrono_literals;

    App::App() :
        errorCallback(std::bind(&App::onFatalError, this, std::placeholders::_1)),
        preCrashCallback(std::bind(&App::preCrash, this)),
        log(errorCallback, preCrashCallback)
        
    {
      
    }

    App::~App()
    {
    }

    void App::run()
    {
        // let the client initialize
        onInit();
    }

    // preCrash
    void App::preCrash()
    {
        // let the client throw up a warning if it can
        onCrash();

#ifndef NDEBUG
#if (defined(WIN32) || defined(_WIN32) || defined(__WIN32__))
        __debugbreak();
#endif
#endif
    }

    // onFatalError
    void App::onFatalError(g3::FatalMessagePtr fatal_message)
    {
        LOG(CRITICAL) << fatal_message.get()->toString();

        g3::internal::pushFatalMessageToLogger(fatal_message);
    }
} // namespace Jahley